# Generated by Django 4.2.11 on 2024-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_management", "0002_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
