# Generated by Django 4.2.11 on 2024-05-03 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_management", "0003_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPerformance",
        ),
    ]
