# Generated by Django 4.2.11 on 2024-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_management", "0005_historicalperformance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="quality_rating_avg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
