# Generated by Django 4.2.11 on 2024-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendor_management",
            "0007_alter_historicalperformance_average_response_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
