# Generated by Django 4.2.11 on 2024-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendor_management",
            "0008_alter_vendor_address_alter_vendor_contact_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
