# Generated by Django 4.2.11 on 2024-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_management", "0009_alter_purchaseorder_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
